language: python

python:
  - 3.6

addons:
  - postgresql: "9.5"


install:
  - pip install -r requirements.txt

before_script:
  - sudo psql -c "ALTER USER postgres PASSWORD 'Amb9Y9sXHgG993NW';"
  - psql -c "CREATE DATABASE modebate;" -U postgres
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
env:
  - DJANGO=1.9.10

script: python manage.py test --keepdb
