language: python

python:
  - 3.6

addons:
  - postgresql: "9.5"


install:
  - pip install -r requirements.txt

before_script:
  - sudo -u postgres -i psql -c "ALTER USER postgres PASSWORD '"${!dbpass}';"
  - psql -c "CREATE DATABASE modebate;" -U postgres
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
env:
  - DJANGO=2.0.3

script: python manage.py test --keepdb
