version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD
        ports:
            - "5432:5432"
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        links:
            - "db:db"
        environment:
            - SECRET_KEY
            - dbpass
            - GR_ARGUMENTFORM
            - GR_DEBATEFORM
            - GR_TOPICFORM
            - GR_SIGNUPFORM
            - GR_ADDEMAILFORM
            - GR_REPORTFORM
            - RECAPTCHA_PUBLIC
            - RECAPTCHA_PRIVATE
            - POSTGRES_PASSWORD
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
