# Generated by Django 2.0.2 on 2018-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='approvalstatus',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='argument',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='argument',
            name='side',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debate',
            name='approvalstatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='debate',
            name='karma',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='debate',
            name='slvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='debslvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slvl',
            field=models.IntegerField(default=0),
        ),
    ]
