# Generated by Django 2.0.2 on 2018-03-07 22:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(max_length=200000)),
                ('approvedstatus', models.IntegerField(default=0)),
                ('order', models.IntegerField(default='0')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 9934))),
            ],
        ),
        migrations.CreateModel(
            name='DebateRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slvl', models.IntegerField(default='0')),
                ('question', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=200000)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 10433))),
            ],
        ),
        migrations.CreateModel(
            name='TopicRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='The description has not been set yet.', max_length=600000)),
                ('private', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 10932))),
                ('moderators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicrevisions_owned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='argument',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='argument',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 8936)),
        ),
        migrations.AddField(
            model_name='argument',
            name='edited_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 8936)),
        ),
        migrations.AddField(
            model_name='argument',
            name='order',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='debate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 7439)),
        ),
        migrations.AddField(
            model_name='debate',
            name='edited_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 7439)),
        ),
        migrations.AddField(
            model_name='debate',
            name='karma',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='debate',
            name='users_upvoting',
            field=models.ManyToManyField(related_name='debates_upvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='edited_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 5941)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 17, 19, 50, 5941)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='moderators',
            field=models.ManyToManyField(related_name='moderator_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='topicrevision',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='debates.Topic'),
        ),
        migrations.AddField(
            model_name='debaterevision',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='debates.Debate'),
        ),
        migrations.AddField(
            model_name='debaterevision',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debaterevisions_contained', to='debates.Topic'),
        ),
        migrations.AddField(
            model_name='argumentrevision',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='debates.Argument'),
        ),
    ]
