# Generated by Django 2.0.2 on 2018-03-06 21:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=200000),
        ),
        migrations.AlterField(
            model_name='argument',
            name='body',
            field=tinymce.models.HTMLField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='The description has not been set yet.', max_length=600000),
        ),
    ]
