# Generated by Django 2.0.2 on 2018-03-07 22:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_auto_20180307_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 768820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='argument',
            name='edited_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 768820, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='argumentrevision',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 769318, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='debate',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 767323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='debate',
            name='edited_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 767323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='debaterevision',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 770317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 765326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='edited_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 765326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='topicrevision',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 22, 21, 32, 770816, tzinfo=utc)),
        ),
    ]
