# Generated by Django 2.0.2 on 2018-03-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0003_debate_modnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisiondata',
            name='bodchg',
            field=models.TextField(blank=True, max_length=400000),
        ),
        migrations.AddField(
            model_name='revisiondata',
            name='titchg',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
