# Generated by Django 2.0.2 on 2018-03-23 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0004_auto_20180316_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='created_on',
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now),
        ),
    ]
