# Generated by Django 2.0.2 on 2018-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0004_auto_20180307_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='approvedstatus',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='topic',
            name='debslvl',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slvl',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='debates.Debate'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='debates.Topic'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='debates.Topic'),
        ),
        migrations.AlterField(
            model_name='debaterevision',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debaterevisions', to='debates.Topic'),
        ),
    ]
