# Generated by Django 2.0.2 on 2018-03-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0005_auto_20180307_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
