# Generated by Django 2.0.2 on 2018-03-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0005_auto_20180323_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.SlugField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
