# Generated by Django 2.0.2 on 2018-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0006_auto_20180325_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisiondata',
            name='bodchg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='revisiondata',
            name='titchg',
            field=models.TextField(blank=True),
        ),
    ]
