# Generated by Django 2.0.2 on 2018-03-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0006_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentrevision',
            name='ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='debaterevision',
            name='ip',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='topicrevision',
            name='ip',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
