# Generated by Django 2.0.2 on 2018-03-28 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0007_auto_20180325_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='arguments',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debate',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='debates',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
