# Generated by Django 2.0.2 on 2018-03-10 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0008_debate_approved_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='users_upvoting',
            field=models.ManyToManyField(blank=True, related_name='debates_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
