# Generated by Django 2.0.2 on 2018-03-10 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debates', '0010_auto_20180309_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='users_downvoting',
            field=models.ManyToManyField(blank=True, related_name='debates_downvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
