# Generated by Django 2.0.2 on 2018-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0012_argument_modnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='side',
            field=models.IntegerField(default='0'),
        ),
    ]
