# Generated by Django 2.0.2 on 2018-03-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0013_argument_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='slvl',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='debslvl',
            field=models.IntegerField(default='1'),
        ),
    ]
