# Generated by Django 2.0.2 on 2018-03-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0014_auto_20180311_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='approvedstatus',
            field=models.IntegerField(default=1),
        ),
    ]
