# Generated by Django 2.0.2 on 2018-03-12 03:10

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0015_auto_20180311_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argument',
            name='order',
        ),
        migrations.AlterField(
            model_name='argument',
            name='approvedstatus',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='debate',
            name='approved_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debate',
            name='karma',
            field=models.IntegerField(db_index=True, default='0'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='users_downvoting',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='debates_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debate',
            name='users_upvoting',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='debates_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
