# Generated by Django 2.0.2 on 2018-03-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0016_auto_20180311_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
