# Generated by Django 2.0.2 on 2018-03-12 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0017_auto_20180311_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='users_downvoting',
            field=models.ManyToManyField(blank=True, related_name='debates_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debate',
            name='users_upvoting',
            field=models.ManyToManyField(blank=True, related_name='debates_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
