# Generated by Django 2.0.2 on 2018-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0018_auto_20180311_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='order',
            field=models.IntegerField(db_index=True, default='0'),
        ),
    ]
