# Generated by Django 2.0.2 on 2018-03-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0019_argument_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
