# Generated by Django 2.0.2 on 2018-03-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('debates', '0020_auto_20180312_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reversion.Revision')),
            ],
        ),
        migrations.RemoveField(
            model_name='argumentrevision',
            name='argument',
        ),
        migrations.RemoveField(
            model_name='debaterevision',
            name='debate',
        ),
        migrations.RemoveField(
            model_name='debaterevision',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicrevision',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='topicrevision',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topicrevision',
            name='topic',
        ),
        migrations.DeleteModel(
            name='ArgumentRevision',
        ),
        migrations.DeleteModel(
            name='DebateRevision',
        ),
        migrations.DeleteModel(
            name='TopicRevision',
        ),
    ]
