# Generated by Django 2.2 on 2020-04-10 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddebate',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debates.Debate'),
        ),
        migrations.AddField(
            model_name='saveddebate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedargument',
            name='argument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debates.Argument'),
        ),
        migrations.AddField(
            model_name='savedargument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modaction',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modlogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='saveda',
            field=models.ManyToManyField(blank=True, related_name='usaved', through='accounts.SavedArgument', to='debates.Argument'),
        ),
        migrations.AddField(
            model_name='user',
            name='savedd',
            field=models.ManyToManyField(blank=True, related_name='usaved', through='accounts.SavedDebate', to='debates.Debate'),
        ),
        migrations.AddField(
            model_name='user',
            name='stopics',
            field=models.ManyToManyField(blank=True, related_name='susers', to='debates.Topic'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
