# Generated by Django 2.0.2 on 2018-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='approvedargs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='modstatus',
            field=models.IntegerField(default=0),
        ),
    ]
