# Generated by Django 2.2 on 2020-04-10 20:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200329_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stopics',
            field=models.ManyToManyField(blank=True, default=accounts.models.get_default_topics, related_name='susers', to='debates.Topic'),
        ),
    ]
