# Generated by Django 2.0.2 on 2018-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_approvedargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modstatus',
            field=models.IntegerField(default='0'),
        ),
    ]
