# Generated by Django 2.0.2 on 2018-03-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180315_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bandate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
