# Generated by Django 2.2 on 2020-04-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200410_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stopics',
            field=models.ManyToManyField(blank=True, related_name='susers', to='debates.Topic'),
        ),
    ]
