# Generated by Django 2.0.2 on 2018-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bannote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.IntegerField(default=0),
        ),
    ]
