# Generated by Django 2.0.2 on 2018-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_ban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ban',
            new_name='active',
        ),
    ]
