# Generated by Django 2.0.2 on 2018-03-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0004_auto_20180316_0957'),
        ('accounts', '0007_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stopics',
            field=models.ManyToManyField(blank=True, related_name='susers', to='debates.Topic'),
        ),
    ]
