# Generated by Django 2.0.4 on 2018-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bandate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
