# Generated by Django 2.0.4 on 2018-04-05 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180405_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=10000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='bandate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='modaction',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modlogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
