# Generated by Django 2.0.4 on 2018-04-07 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180405_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaction',
            name='until',
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True),
        ),
    ]
