# Generated by Django 2.0.4 on 2018-04-07 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_modaction_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='modaction',
            name='until',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
