# Generated by Django 2.0.4 on 2018-04-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180407_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modaction',
            options={'ordering': ['-date']},
        ),
    ]
