# Generated by Django 2.0.4 on 2018-04-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180407_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modaction',
            old_name='note',
            new_name='modnote',
        ),
    ]
