# Generated by Django 2.0.4 on 2018-04-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180407_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaction',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
